<?php

namespace App\Http\Controllers\Staff;

use App\Http\Controllers\Controller;
use App\Models\ReportCard;
use App\Models\Student;
use App\Models\School;
use App\Models\SchoolMarkingPeriod;
use App\Models\GradeLevel; // As per your ReportCard model
use App\Models\Staff;
use App\Models\StudentEnrollment; // For fetching students
use Exception;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;
use Illuminate\Validation\ValidationException;
use Illuminate\View\View;
use Illuminate\Support\Facades\DB;

class ReportCardController extends Controller
{
    /**
     * Display a listing of the report cards.
     *
     * @param Request $request
     * @return View
     * @throws AuthorizationException
     */
    public function index(Request $request): View
    {
        $this->authorize('view report_cards');

        $currentSchoolId = session('current_school_id');
        $currentSyear = session('current_syear', date('Y'));

        // Fallback if session variables are not set (though ideally, they should be guaranteed by middleware or earlier logic)
        if (!$currentSchoolId || !$currentSyear) {
            Log::warning('Current school ID or syear not found in session for ReportCard index.', ['user_id' => Auth::id()]);
            // Redirect or show an error, or fetch all if that's desired (though risky)
            // For now, we'll proceed, but queries might return empty or all data if not filtered.
            // It's better to enforce these session variables.
        }

        $query = ReportCard::query()
            ->with(['student', 'markingPeriod', 'gradeLevel', 'school', 'generator'])
            ->where('school_id', $currentSchoolId)
            ->where('syear', $currentSyear);

        // --- Apply Filters ---
        if ($request->filled('student_search_term')) {
            $searchTerm = '%' . $request->student_search_term . '%';
            $query->whereHas('student', function ($q) use ($searchTerm) {
                $q->where(DB::raw("CONCAT(COALESCE(first_name,''), ' ', COALESCE(middle_name,''), ' ', COALESCE(last_name,''))"), 'LIKE', $searchTerm)
                    ->orWhere('username', 'LIKE', $searchTerm);
            });
        }
        if ($request->filled('marking_period_id_filter')) {
            $query->where('marking_period_id', $request->marking_period_id_filter);
        }
        if ($request->filled('grade_id_filter')) {
            $query->where('grade_id', $request->grade_id_filter);
        }
        if ($request->filled('is_published_filter')) {
            $query->where('is_published', $request->is_published_filter === '1');
        }

        // --- Initial Sorting ---
        $sortBy = $request->input('sort_by', 'created_at');
        $sortOrder = $request->input('sort_order', 'desc');
        $allowedSorts = ['student_id', 'marking_period_id', 'grade_id', 'is_published', 'created_at'];

        if (in_array($sortBy, $allowedSorts)) {
            $query->orderBy($sortBy, $sortOrder);
        } else {
            $query->orderBy('created_at', 'desc');
        }

        $reportCards = $query->get();
        $currentUser = Auth::guard('staff')->user(); // Use staff guard

        // 1. Define Headers for AdminLTE Datatable
        $heads = [
            'ID', 'Student', 'Marking Period', 'Grade Level',
            ['label' => 'Published', 'width' => 8, 'class' => 'text-center'],
            'Generated By', 'Created At',
            ['label' => 'Actions', 'no-export' => true, 'width' => 15, 'orderable' => false, 'class' => 'text-center'],
        ];

        // 2. Build the data array for AdminLTE Datatable
        $data = [];
        foreach ($reportCards as $reportCard) {
            $studentName = $reportCard->student ? e(trim(($reportCard->student->first_name ?? '') . ' ' . ($reportCard->student->middle_name ?? '') . ' ' . ($reportCard->student->last_name ?? ''))) : 'N/A';
            $studentUsername = $reportCard->student ? e($reportCard->student->username) : '';
            $studentHtml = "N/A";
            if ($reportCard->student && $reportCard->student_id) {
                $studentShowRoute = route('staff.students.show', $reportCard->student_id);
                $studentHtml = "<a href='{$studentShowRoute}'>{$studentName}</a><small class='d-block text-muted'>{$studentUsername}</small>";
            } elseif($reportCard->student) {
                $studentHtml = "{$studentName}<small class='d-block text-muted'>{$studentUsername}</small>";
            }

            $markingPeriodTitle = $reportCard->markingPeriod ? e($reportCard->markingPeriod->title) : 'N/A';
            $gradeLevelTitle = $reportCard->gradeLevel ? e($reportCard->gradeLevel->title) : 'N/A';
            $generatorName = $reportCard->generator ? e(trim(($reportCard->generator->first_name ?? '') . ' ' . ($reportCard->generator->last_name ?? ''))) : 'N/A';
            $publishedHtml = $reportCard->is_published ? '<span class="badge badge-success">Yes</span>' : '<span class="badge badge-warning">No</span>';

            $actionsHtml = "<nobr>";
            if ($currentUser && $currentUser->can('show report_cards', $reportCard)) {
                $actionsHtml .= "<a href='" . route('staff.reportcards.show', $reportCard->id) . "' class='btn btn-xs btn-info mr-1' title='View Report Card'><i class='fa fa-eye'></i></a>";
            }
            if ($currentUser && $currentUser->can('edit report_cards', $reportCard)) {
                $actionsHtml .= "<a href='" . route('staff.reportcards.edit', $reportCard->id) . "' class='btn btn-xs btn-primary mr-1' title='Edit Report Card'><i class='fa fa-edit'></i></a>";
            }
            if ($currentUser && $currentUser->can('publish report_cards', $reportCard)) {
                $publishRoute = route('staff.reportcards.togglePublish', $reportCard->id);
                $publishIcon = $reportCard->is_published ? 'fa-toggle-off' : 'fa-toggle-on';
                $publishTitle = $reportCard->is_published ? 'Unpublish' : 'Publish';
                $publishBtnClass = $reportCard->is_published ? 'btn-warning' : 'btn-success';
                $actionsHtml .= "<form action='{$publishRoute}' method='POST' class='d-inline m-0 p-0' onsubmit='return confirm(\"Are you sure you want to " . strtolower($publishTitle) . " this report card?\");'>".csrf_field().method_field('PATCH')."<button type='submit' class='btn btn-xs {$publishBtnClass} mr-1' title='{$publishTitle}'><i class='fas {$publishIcon}'></i></button></form>";
            }
            if ($currentUser && $currentUser->can('delete report_cards', $reportCard)) {
                $actionsHtml .= "<button type='button' class='btn btn-xs btn-danger delete-reportcard-btn' data-id='{$reportCard->id}' title='Delete Report Card'><i class='fa fa-trash'></i></button>";
            }
            $actionsHtml .= "</nobr>";

            $data[] = [
                $reportCard->id, $studentHtml, $markingPeriodTitle, $gradeLevelTitle,
                $publishedHtml, $generatorName,
                $reportCard->created_at ? $reportCard->created_at->format('Y-m-d H:i') : 'N/A',
                $actionsHtml,
            ];
        }

        $config = [ /* ... (config array remains the same) ... */
            'data' => $data,
            'order' => [[6, 'desc']],
            'columns' => [
                null, null, null, null,
                ['className' => 'text-center'],
                null, null,
                ['orderable' => false, 'searchable' => false, 'className' => 'text-center'],
            ],
            'paging' => true, 'lengthChange' => true, 'lengthMenu' => [10, 25, 50, 100, 250],
            'searching' => true, 'info' => true, 'responsive' => true, 'autoWidth' => false,
        ];

        Log::info('ReportCard index viewed', ['user_id' => Auth::guard('staff')->id(), 'filters' => $request->all(), 'result_count' => count($data)]);

        $markingPeriodsForFilter = SchoolMarkingPeriod::where('school_id', $currentSchoolId)->where('syear', $currentSyear)->orderBy('title')->pluck('title', 'marking_period_id');
        $gradeLevelsForFilter = GradeLevel::where('school_id', $currentSchoolId)->where('school_syear', $currentSyear)->orderBy('title')->pluck('title', 'id');
        $publishStatuses = ['' => 'All Statuses', '1' => 'Published', '0' => 'Not Published'];

        return view('pages.staff.reports.index', compact( // Corrected view path
            'heads', 'config', 'reportCards',
            'markingPeriodsForFilter', 'gradeLevelsForFilter', 'publishStatuses',
            'currentSchoolId', 'currentSyear'
        ));
    }

    /**
     * Show the form for creating a new report card.
     *
     * @param Request $request
     * @return View
     * @throws AuthorizationException
     */
    public function create(Request $request): View|RedirectResponse
    {
        $this->authorize('create report_cards');

        $currentSchoolId = session('current_school_id');
        $currentSyear = session('current_syear', date('Y'));

        if (!$currentSchoolId || !$currentSyear) {
            return redirect()->route('staff.dashboard') // Or a more appropriate error page
            ->with('error', 'Current school or academic year not set. Please select them first.');
        }

        $studentsQuery = Student::query()->select('students.id', 'students.first_name', 'students.middle_name', 'students.last_name', 'students.username')
            ->join('student_enrollment', 'students.id', '=', 'student_enrollment.student_id')
            ->where('student_enrollment.school_id', $currentSchoolId)
            ->where('student_enrollment.syear', $currentSyear)
            ->where('student_enrollment.start_date', '<=', now())
            ->where(function ($q) {
                $q->where('student_enrollment.end_date', '>=', now())
                    ->orWhereNull('student_enrollment.end_date');
            });

        if ($request->has('grade_id_filter_form')) { // Use a distinct name for form filter
            $studentsQuery->where('student_enrollment.grade_id', $request->grade_id_filter_form);
        }

        $students = $studentsQuery->distinct()->orderBy('students.last_name')->orderBy('students.first_name')->get()
            ->mapWithKeys(function($student){
                $name = trim(($student->first_name ?? '') . ' ' . ($student->middle_name ?? '') . ' ' . ($student->last_name ?? ''));
                return [$student->id => $name . ' (' . ($student->username ?? 'N/A') . ')'];
            });

        $markingPeriods = SchoolMarkingPeriod::where('school_id', $currentSchoolId)->where('syear', $currentSyear)->orderBy('title')->pluck('title', 'marking_period_id');
        $gradeLevels = GradeLevel::where('school_id', $currentSchoolId)->where('school_syear', $currentSyear)->orderBy('title')->pluck('title', 'id');

        return view('pages.staff.reportcards.create', compact('students', 'markingPeriods', 'gradeLevels', 'currentSchoolId', 'currentSyear'));
    }

    /**
     * Store a newly created report card in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     * @throws AuthorizationException
     * @throws ValidationException
     */
    public function store(Request $request): RedirectResponse
    {
        $this->authorize('create report_cards');

        $validatedData = $request->validate([
            'syear' => 'required|numeric|digits:4',
            'school_id' => 'required|exists:schools,id',
            'student_id' => ['required', 'exists:students,id',
                Rule::unique('report_cards')->where(function ($query) use ($request) {
                    return $query->where('student_id', $request->student_id)
                        ->where('marking_period_id', $request->marking_period_id)
                        ->where('syear', $request->syear)
                        ->where('school_id', $request->school_id);
                })
            ],
            'marking_period_id' => 'required|exists:school_marking_periods,marking_period_id',
            'grade_id' => 'nullable|exists:school_gradelevels,id',
            'subject_grades_structured' => 'nullable|array', // Expect an array for structured input
            'subject_grades_structured.*.subject_id' => 'required_with:subject_grades_structured|exists:subjects,subject_id',
            'subject_grades_structured.*.grade' => 'nullable|string|max:10', // Example validation
            'subject_grades_structured.*.comment' => 'nullable|string|max:255', // Example validation
            'subject_grades' => 'nullable|json', // Allow raw JSON input as fallback
            'comments' => 'nullable|string',
            'is_published' => 'required|boolean',
        ]);

        return DB::transaction(function () use ($validatedData, $request) {
            $reportCardData = $validatedData;
            $reportCardData['generated_by'] = Auth::guard('staff')->id();

            // Handle subject_grades: prioritize structured input
            if (!empty($validatedData['subject_grades_structured'])) {
                $reportCardData['subject_grades'] = json_encode($validatedData['subject_grades_structured']);
            } elseif (!empty($validatedData['subject_grades'])) {
                // If raw JSON is provided and validated, use it.
                // The 'json' rule already validated it.
                $reportCardData['subject_grades'] = $validatedData['subject_grades'];
            } else {
                $reportCardData['subject_grades'] = null; // Ensure it's null if neither is provided
            }
            unset($reportCardData['subject_grades_structured']); // Don't try to save this to DB

            $reportCard = ReportCard::create($reportCardData);
            Log::info('Report Card created.', ['id' => $reportCard->id, 'user_id' => Auth::guard('staff')->id()]);
            return redirect()->route('staff.reportcards.index')->with('success', 'Report Card created successfully.');
        });
    }

    /**
     * Display the specified report card.
     *
     * @param ReportCard $reportcard
     * @return View
     * @throws AuthorizationException
     */
    public function show(ReportCard $reportcard): View
    {
        $this->authorize('show report_cards', $reportcard);
        $reportcard->load(['student', 'markingPeriod', 'gradeLevel', 'school', 'generator']);
        return view('pages.staff.reportcards.show', compact('reportcard'));
    }

    /**
     * Show the form for editing the specified report card.
     *
     * @param ReportCard $reportcard
     * @return View
     * @throws AuthorizationException
     */
    public function edit(ReportCard $reportcard): View
    {
        $this->authorize('edit report_cards', $reportcard);
        $reportcard->load(['student', 'markingPeriod', 'gradeLevel']);

        $currentSchoolId = $reportcard->school_id;
        $currentSyear = $reportcard->syear;

        // Students list should be relevant to the report card's context
        $students = Student::query()->select('students.id', 'students.first_name', 'students.middle_name', 'students.last_name', 'students.username')
            ->join('student_enrollment', 'students.id', '=', 'student_enrollment.student_id')
            ->where('student_enrollment.school_id', $currentSchoolId)
            ->where('student_enrollment.syear', $currentSyear)
            ->where('student_enrollment.start_date', '<=', now())
            ->where(function ($q) {
                $q->where('student_enrollment.end_date', '>=', now())->orWhereNull('student_enrollment.end_date');
            })
            ->distinct()->orderBy('students.last_name')->orderBy('students.first_name')->get()
            ->mapWithKeys(function($student){
                $name = trim(($student->first_name ?? '') . ' ' . ($student->middle_name ?? '') . ' ' . ($student->last_name ?? ''));
                return [$student->id => $name . ' (' . ($student->username ?? 'N/A') . ')'];
            });

        $markingPeriods = SchoolMarkingPeriod::where('school_id', $currentSchoolId)->where('syear', $currentSyear)->orderBy('title')->pluck('title', 'marking_period_id');
        $gradeLevels = GradeLevel::where('school_id', $currentSchoolId)->where('school_syear', $currentSyear)->orderBy('title')->pluck('title', 'id');

        // Prepare subject_grades for form display if it's structured
        $subject_grades_structured = is_string($reportcard->subject_grades) ? json_decode($reportcard->subject_grades, true) : $reportcard->subject_grades;
        if (json_last_error() !== JSON_ERROR_NONE) {
            $subject_grades_structured = []; // Default to empty array if JSON is invalid
        }


        return view('pages.staff.reportcards.edit', compact('reportcard', 'students', 'markingPeriods', 'gradeLevels', 'subject_grades_structured'));
    }

    /**
     * Update the specified report card in storage.
     *
     * @param Request $request
     * @param ReportCard $reportcard
     * @return RedirectResponse
     * @throws AuthorizationException
     * @throws ValidationException
     */
    public function update(Request $request, ReportCard $reportcard): RedirectResponse
    {
        $this->authorize('edit report_cards', $reportcard);

        $validatedData = $request->validate([
            'student_id' => ['required', 'exists:students,id',
                Rule::unique('report_cards')->where(function ($query) use ($request, $reportcard) {
                    return $query->where('student_id', $request->student_id)
                        ->where('marking_period_id', $request->marking_period_id)
                        ->where('syear', $reportcard->syear)
                        ->where('school_id', $reportcard->school_id);
                })->ignore($reportcard->id)
            ],
            'marking_period_id' => 'required|exists:school_marking_periods,marking_period_id',
            'grade_id' => 'nullable|exists:school_gradelevels,id',
            'subject_grades_structured' => 'nullable|array',
            'subject_grades_structured.*.subject_id' => 'required_with:subject_grades_structured|exists:subjects,subject_id',
            'subject_grades_structured.*.grade' => 'nullable|string|max:10',
            'subject_grades_structured.*.comment' => 'nullable|string|max:255',
            'subject_grades' => 'nullable|json',
            'comments' => 'nullable|string',
            'is_published' => 'required|boolean',
        ]);

        return DB::transaction(function () use ($validatedData, $request, $reportcard) {
            $updateData = $validatedData;

            if (!empty($validatedData['subject_grades_structured'])) {
                $updateData['subject_grades'] = json_encode($validatedData['subject_grades_structured']);
            } elseif (isset($validatedData['subject_grades'])) { // Check if raw JSON was passed and validated
                $updateData['subject_grades'] = $validatedData['subject_grades'];
            } else {
                // If neither structured nor raw JSON is provided, but you want to clear existing, set to null
                // $updateData['subject_grades'] = null;
                // Or, if you want to preserve existing if nothing new is sent, remove it from $updateData
                unset($updateData['subject_grades']);
            }
            unset($updateData['subject_grades_structured']);


            $reportcard->update($updateData);
            Log::info('Report Card updated.', ['id' => $reportcard->id, 'user_id' => Auth::guard('staff')->id()]);
            return redirect()->route('staff.reportcards.index')->with('success', 'Report Card updated successfully.');
        });
    }

    /**
     * Remove the specified report card from storage.
     *
     * @param ReportCard $reportcard
     * @return JsonResponse|RedirectResponse
     * @throws AuthorizationException
     */
    public function destroy(ReportCard $reportcard): JsonResponse|RedirectResponse
    {
        $this->authorize('delete report_cards', $reportcard);

        return DB::transaction(function () use ($reportcard) {
            $reportcard->delete();
            Log::info('Report Card deleted.', ['id' => $reportcard->id, 'user_id' => Auth::guard('staff')->id()]);

            if (request()->ajax()) {
                return response()->json(['success' => true, 'message' => 'Report Card deleted successfully.']);
            }
            return redirect()->route('staff.reportcards.index')->with('success', 'Report Card deleted successfully.');
        });
    }

    /**
     * Toggle the publish status of a report card.
     *
     * @param ReportCard $reportcard
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function togglePublish(ReportCard $reportcard): RedirectResponse
    {
        $this->authorize('publish report_cards', $reportcard);

        return DB::transaction(function () use ($reportcard) {
            $reportcard->is_published = !$reportcard->is_published;
            $reportcard->save();
            $statusMessage = $reportcard->is_published ? 'published' : 'unpublished';
            Log::info('Report Card publish status toggled.', ['id' => $reportcard->id, 'published' => $reportcard->is_published, 'user_id' => Auth::guard('staff')->id()]);
            return redirect()->back()->with('success', "Report Card successfully {$statusMessage}.");
        });
    }
}
