<?php

namespace App\Models;

use Database\Factories\StaffFactory; // Corrected namespace if factory is in Database\Factories
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection as EloquentCollection; // Eloquent Collection alias
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable; // Recommended for Authenticatable models
use Illuminate\Support\Carbon;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

// Assuming these models exist in App\Models namespace
// use App\Models\School; // Already imported
// use App\Models\UserProfile; // If you create this model
// use App\Models\AuditLog;
// use App\Models\Exam;
// use App\Models\ReportCard;
// use App\Models\Result;
// use App\Models\ResultImport;
// use App\Models\MarkingScale;
// use App\Models\TeacherSubjectGrade;

/**
 * Represents a staff member in the application.
 *
 * Corresponds to the 'staff' database table.
 * Uses Spatie Permissions for role management.
 *
 * @property int $staff_id The unique identifier for the staff member (Primary Key).
 * @property int $syear The school year associated with this record (e.g., 2024 for 2024-2025).
 * @property int|null $current_school_id Foreign key to the schools table for the staff's current school.
 * @property string|null $title The staff member's title (e.g., Mr., Ms., Dr.).
 * @property string $first_name The staff member's first name.
 * @property string $last_name The staff member's last name.
 * @property string|null $middle_name The staff member's middle name.
 * @property string|null $name_suffix Suffix for the name (e.g., Jr., Sr., III).
 * @property string|null $username The login username for the staff member (typically lowercase).
 * @property string|null $password The hashed password for the staff member.
 * @property string|null $email The email address of the staff member.
 * @property string|null $phone A custom text field for additional information.
 * @property int|null $current_school_syear The school year associated with the current school assignment (part of composite FK).
 * @property string|null $profile Legacy profile/role field (consider relying solely on Spatie roles).
 * @property string|null $schools Potentially stores associated school information (consider a dedicated relationship if complex).
 * @property Carbon|null $last_login Timestamp of the last successful login.
 * @property int|null $failed_login Count of consecutive failed login attempts.
 * @property int|null $profile_id Legacy profile ID (consider linking to UserProfile model or relying on Spatie roles).
 * @property int|null $rollover_id ID used during data rollover processes from a previous year/system.
 * @property string|null $photo_path Path to the staff member's photo, relative to storage.
 * @property Carbon|null $created_at Timestamp of creation.
 * @property Carbon|null $updated_at Timestamp of last update.
 *
 * @property-read School|null $school The current school this staff member is assigned to.
 * @property-read UserProfile|null $userProfile The legacy user profile associated with this staff.
 * @property-read EloquentCollection|Role[] $roles Spatie roles assigned to this staff member.
 * @property-read EloquentCollection|Permission[] $permissions Direct permissions assigned to this staff member.
 * @property-read EloquentCollection|AuditLog[] $auditLogs Audit logs generated by this staff member.
 * @property-read EloquentCollection|Exam[] $createdExams Exams created by this staff member.
 * @property-read EloquentCollection|ReportCard[] $generatedReportCards Report cards generated by this staff member.
 * @property-read EloquentCollection|Result[] $gradedResults Exam results graded by this staff member.
 * @property-read EloquentCollection|ResultImport[] $resultImports Result imports performed by this staff member.
 * @property-read EloquentCollection|MarkingScale[] $createdMarkingScales Marking scales created by this staff member.
 * @property-read EloquentCollection|TeacherSubjectGrade[] $teachingAssignments Teaching assignments for this staff member.
 * @property-read string $full_name Accessor for the full name.
 *
 * @method static StaffFactory factory($count = null, $state = [])
 * @method static Builder|Staff newModelQuery()
 * @method static Builder|Staff newQuery()
 * @method static Builder|Staff query()
 * @method static Builder|Staff where(string $column, mixed $operator = null, mixed $value = null, string $boolean = 'and')
 * @method static Builder|Staff whereUsername(string $value)
 * @method static Builder|Staff whereStaffId(int $value)
 * @method static Builder|Staff whereEmail(string $value)
 * @method static Builder|Staff whereSyear(int $value)
 * @method static Builder|Staff role($roles, string $guard = null) Scope for Spatie roles.
 */
class Staff extends Authenticatable
{
    use HasFactory, HasRoles, Notifiable; // Added Notifiable

    /**
     * The guard name used by Spatie permissions.
     * Essential for multi-authentication setups if 'staff' is a custom guard.
     *
     * @var string
     */
    protected string $guard_name = 'staff'; // Or 'web' if using the default web guard

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'staff';

    /**
     * The primary key associated with the table.
     *
     * @var string
     */
    protected $primaryKey = 'staff_id';

    /**
     * Indicates if the model's ID is auto-incrementing.
     *
     * @var bool
     */
    public $incrementing = true;

    /**
     * The data type of the auto-incrementing ID.
     * Eloquent maps BIGINT to int internally, but 'string' can be used for unsigned big integers
     * if precision with very large numbers outside PHP's max int on 32-bit systems is a concern.
     * 'int' is generally fine for primary keys.
     *
     * @var string
     */
    protected $keyType = 'int';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = true;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'syear',
        'current_school_id',
        'title',
        'first_name',
        'last_name',
        'middle_name',
        'name_suffix',
        'username',
        'password', // Handled by mutator
        'email',
        'phone',
        'current_school_syear',
        'profile', // Legacy field, Spatie roles preferred
        'schools', // Legacy field, consider relationship if needed
        'last_login', // Typically updated programmatically
        'failed_login', // Typically updated programmatically
        'profile_id', // Legacy field
        'rollover_id',
        'photo_path',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token', // Standard Laravel field
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'syear'                 => 'integer', // DECIMAL(4,0) -> integer
        'current_school_id'     => 'integer', // BIGINT UNSIGNED -> integer
        // 'staff_id' primary key is already int by $keyType
        'current_school_syear'  => 'integer', // DECIMAL(4,0) -> integer
        'last_login'            => 'datetime',
        'failed_login'          => 'integer',
        'profile_id'            => 'integer', // BIGINT UNSIGNED -> integer
        'rollover_id'           => 'integer', // BIGINT UNSIGNED -> integer
        'created_at'            => 'datetime',
        'updated_at'            => 'datetime',
        // For Laravel 9+, 'password' => 'hashed' is recommended over a manual mutator.
        // If using Laravel < 9 or specific logic is needed, the mutator is fine.
    ];

    /**
     * Automatically hash the password attribute when it is set.
     *
     * @param string|null $value The password to set.
     * @return void
     */
    public function setPasswordAttribute(?string $value): void
    {
        if (!empty($value)) {
            // Consider using Laravel's 'hashed' cast in $casts for versions 9+
            $this->attributes['password'] = Hash::make($value);
        } else {
            // If an empty value is passed, explicitly set to null
            // This prevents hashing an empty string if that's not desired.
            $this->attributes['password'] = null;
        }
    }

    /**
     * Accessor to ensure the username is always lowercase when retrieved.
     *
     * @param string|null $value The original username value from the database.
     * @return string|null The username converted to lowercase.
     */
    public function getUsernameAttribute(?string $value): ?string
    {
        return $value ? strtolower($value) : null;
    }

    // =========================================================================
    // Relationships
    // =========================================================================

    /**
     * Get the current school this staff member is assigned to.
     * IMPORTANT: The 'staff' table uses a composite foreign key (`current_school_id`, `current_school_syear`)
     * to reference the `schools` table's composite primary key (`id`, `syear`).
     * Standard Eloquent `belongsTo` primarily uses single keys. This relationship links `current_school_id` to `schools.id`.
     * You MUST ensure the `current_school_syear` from this staff model matches the `syear` of the fetched School model
     * in your application logic or through query constraints if strict year matching is required for this relation.
     *
     * @return BelongsTo
     */
    public function school(): BelongsTo
    {
        return $this->belongsTo(School::class, 'current_school_id', 'id');
        // To enforce year matching directly in the relationship (more complex):
        // You might need a custom relation type or add a global scope to the School model
        // or apply ->where('syear', $this->current_school_syear) when querying this relation.
    }

    /**
     * Get the legacy user profile associated with this staff member.
     * Consider phasing out if Spatie roles cover all needs.
     *
     * @return BelongsTo
     */
    public function userProfile(): BelongsTo
    {
        return $this->belongsTo(UserProfile::class, 'profile_id', 'id');
    }

    /**
     * Get the audit logs created by this staff member.
     *
     * @return HasMany
     */
    public function auditLogs(): HasMany
    {
        return $this->hasMany(AuditLog::class, 'user_id', 'staff_id');
    }

    /**
     * Get the exams created by this staff member.
     *
     * @return HasMany
     */
    public function createdExams(): HasMany
    {
        return $this->hasMany(Exam::class, 'created_by', 'staff_id');
    }

    /**
     * Get the report cards generated by this staff member.
     *
     * @return HasMany
     */
    public function generatedReportCards(): HasMany
    {
        return $this->hasMany(ReportCard::class, 'generated_by', 'staff_id');
    }

    /**
     * Get the exam results graded by this staff member.
     *
     * @return HasMany
     */
    public function gradedResults(): HasMany
    {
        return $this->hasMany(Result::class, 'graded_by', 'staff_id');
    }

    /**
     * Get the result imports performed by this staff member.
     *
     * @return HasMany
     */
    public function resultImports(): HasMany
    {
        // Assuming ResultImport model exists
        return $this->hasMany(ResultImport::class, 'imported_by', 'staff_id');
    }

    /**
     * Get the marking scales created by this staff member.
     *
     * @return HasMany
     */
    public function createdMarkingScales(): HasMany
    {
        return $this->hasMany(MarkingScale::class, 'created_by', 'staff_id');
    }

    /**
     * Get the teaching assignments for this staff member.
     * (Links to teacher_subject_grade table)
     *
     * @return HasMany
     */
    public function teachingAssignments(): HasMany
    {
        // Assuming TeacherSubjectGrade model exists
        return $this->hasMany(TeacherSubjectGrade::class, 'staff_id', 'staff_id');
    }

    // Note: Relationships for 'billing_fees' and 'billing_payments' are omitted
    // because their 'created_by' columns are TEXT, not suitable for direct Eloquent foreign keys.
    // Custom logic would be needed if these relationships are required.

    // =========================================================================
    // AdminLTE Integration Methods (or general UI helpers)
    // =========================================================================

    /**
     * Get a description for AdminLTE (or similar UI).
     * Prefers Spatie roles, falls back to the legacy 'profile' field.
     *
     * @return string
     */
    public function adminlte_desc(): string
    {
        // Ensure roles are loaded if you often access this without eager loading.
        // $this->loadMissing('roles');
        if ($this->relationLoaded('roles') && $this->roles->isNotEmpty()) {
            return $this->getRoleNames()->implode(', ');
        }
        return $this->profile ?? 'Staff'; // Fallback gracefully
    }

    /**
     * Get the image path for AdminLTE (or similar UI).
     * Uses the 'photo_path' field if available and file exists, otherwise provides a default.
     *
     * @return string
     */
    public function adminlte_image(): string
    {
        $defaultAvatar = asset('img/default-avatar.png'); // Ensure this default image exists in public/img

        if ($this->photo_path) {
            // Assuming photo_path stores path relative to 'storage/app/public/'
            // e.g., 'staff_photos/avatar.jpg'
            if (Storage::disk('public')->exists($this->photo_path)) {
                return Storage::disk('public')->url($this->photo_path);
            } else {
                Log::warning('Staff photo file missing from public storage.', [
                    'staff_id' => $this->staff_id,
                    'path' => $this->photo_path
                ]);
            }
        }
        return $defaultAvatar;
    }

    // =========================================================================
    // Other Helper Methods
    // =========================================================================

    /**
     * Get the full name of the staff member.
     * Accessor: $staff->full_name
     *
     * @return string
     */
    public function getFullNameAttribute(): string
    {
        $nameParts = [];
        if ($this->title) $nameParts[] = $this->title;
        $nameParts[] = $this->first_name;
        if ($this->middle_name) $nameParts[] = $this->middle_name;
        $nameParts[] = $this->last_name;
        if ($this->name_suffix) $nameParts[] = $this->name_suffix;

        return implode(' ', array_filter($nameParts)); // array_filter removes null/empty parts before imploding
    }

    /**
     * Check if the staff member has a specific role.
     * Convenience method leveraging Spatie's HasRoles trait.
     *
     * @param string|array|\Spatie\Permission\Contracts\Role|Collection $roles
     * @param string|null $guard
     * @return bool
     */
    public function hasExactRoles($roles, string $guard = null): bool
    {
        return $this->hasAllRoles($roles, $guard);
    }
    
    /**
     * Get the user's name for display (e.g., in AdminLTE).
     * Accessor: $staff->name
     *
     * @return string
     */
    public function getNameAttribute(): string
    {
        return $this->getFullNameAttribute();
    }
}
